// Generated by jsScript 1.10.0
(function() {
  Meteor.publish('posts', function() {
    return Posts.find();
  });

  Meteor.publish('attachments', function() {
    return Attachments.find();
  });

}).call(this);
