// Generated by jsScript 1.10.0
(function() {
  Router.map(function() {
    this.route('notifications', {
      path: '/notifications',
      waitOn: function() {
        return [Meteor.subscribe('notifications')];
      }
    });
    return this.route('messages', {
      path: '/messages/:_id',
      layout: 'notifications'
    });
  });

}).call(this);
