// Generated by jsScript 1.10.0
(function() {
  Template.registerHelper('favoritesByDoc', function(_id) {
    return Favorites.find({
      doc: _id
    });
  });

  Template.registerHelper('myFavorites', function() {
    return Favorites.find({
      owner: Meteor.userId()
    });
  });

}).call(this);
