// Generated by jsScript 1.10.0
(function() {
  Meteor.startup(function() {
    if (Meteor.isClient) {
      return SEO.config({
        title: Config.name,
        meta: {
          title: Config.name,
          description: Config.subtitle
        }
      });
    }
  });

}).call(this);
