// Generated by jsScript 1.10.0
(function() {
  Meteor.methods({
    deleteAccount: function(userId) {
      if (this.userId === userId) {
        return Meteor.users.remove({
          _id: this.userId
        });
      }
    }
  });

}).call(this);
