// Generated by jsScript 1.10.0
(function() {
  Favorites.allow({
    insert: function(userId, doc) {
      return doc.owner === userId;
    },
    remove: function(userId, doc) {
      return doc.owner === userId;
    }
  });

}).call(this);
