// Generated by jsScript 1.10.0
(function() {
  Meteor.methods({
    readAllNotifications: function() {
      return Notifications.update({
        read: false
      }, {
        $set: {
          read: true
        }
      }, {
        multi: true
      });
    }
  });

}).call(this);
